name: Building and Testing the Library

on:
  workflow_dispatch: {}
  pull_request:
    paths-ignore:
      - '**.md'
  push:
    branches:
      - master
    paths-ignore:
      - '**.md'

permissions:
  contents: read

jobs:
  run-test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: [ 20, 22, 24 ]
    name: Building and Testing the Library with NodeJS ${{ matrix.node }}
    steps:
      - name: Get source code
        uses: actions/checkout@v5
      - name: Setup NodeJS
        uses: actions/setup-node@v5
        with:
          node-version: ${{ matrix.node }}
          cache: 'npm'
      - name: Install NPM dependencies
        run: npm ci
      - name: Build library
        run: npm run build
      - name: Run test cases
        run: npm test
