name: Testing

on:
  workflow_dispatch: {}
  pull_request:
    paths-ignore:
      - '**.md'
  push:
    branches:
      - master
    paths-ignore:
      - '**.md'

permissions:
  contents: read

jobs:
  run-test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: [ 20, 22, 24 ]
    name: Testing for NodeJS ${{ matrix.node }}
    steps:
      - name: Get source code
        uses: actions/checkout@v5
      - name: Setup NodeJS
        uses: actions/setup-node@v5
        with:
          node-version: ${{ matrix.node }}
          cache: 'npm'
      - name: Install NPM dependencies
        run: npm ci
      - name: Run testing
        run: npm test
